apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: csv-df-s3-
spec:
  entrypoint: csv-df-s3-DAG
  templates:
  - name: csv-df-s3-DAG
    dag:
      tasks:
      - name: csv-df
        template: csv-df-s3-boston
        arguments:
          parameters: [{name: csv_path, value: /S3data/BostonHousing.csv}, 
          {name: output_path, value: /S3data/df.pickle}]
  - name: csv-df-s3-boston
    inputs:
      parameters:
        - name: csv_path
        - name: output_path
      artifacts:
      - name: data-CSV
        path: /S3data
        s3:
          endpoint: argo-artifacts:9000
          insecure: true
          bucket: my-bucket
          key: boston/data
          accessKeySecret:
            name: argo-artifacts
            key: accesskey
          secretKeySecret:
            name: argo-artifacts
            key: secretkey
    container:
      image: csv-df:latest
      imagePullPolicy: Never
      command: [python3]
      args: ["CSV_to_df.py", "--csv_path", "{{inputs.parameters.csv_path}}",
       "--output_path", "{{inputs.parameters.output_path}}"]
    outputs:
      artifacts:
      - name: data-df
        path: /S3data/df.pickle
        s3:
          endpoint: argo-artifacts:9000
          insecure: true
          bucket: my-bucket
          key: boston/data/df.pickle
          accessKeySecret:
            name: argo-artifacts
            key: accesskey
          secretKeySecret:
            name: argo-artifacts
            key: secretkey